// 本预设逐条镜像维护者 dotfiles 的 claude/settings.json 的 permissions 段；
// 调整预设时需同步该文件，避免应用出来的规则与 dotfiles 漂移。
export const RECOMMENDED_PERMISSION_RULES = {
  allow: [],
  ask: [
    "Bash(git push *)",
    "Bash(gh pr merge *)",
    "Bash(gh release *)",
    "Bash(gh repo delete *)",
    "Bash(gh secret *)",
    "Bash(gh workflow run *)",
    "Bash(npm publish *)",
    "Bash(cargo publish *)",
    "Bash(kubectl *)",
  ],
  deny: [
    "Bash(gh auth token*)",
    "Read(**/*.pem)",
    "Edit(**/*.pem)",
    "Read(**/*.key)",
    "Edit(**/*.key)",
    "Read(**/*.p12)",
    "Edit(**/*.p12)",
    "Read(**/*.pfx)",
    "Edit(**/*.pfx)",
    "Read(**/id_rsa*)",
    "Edit(**/id_rsa*)",
    "Read(**/id_ed25519*)",
    "Edit(**/id_ed25519*)",
    "Read(~/.ssh/**)",
    "Edit(~/.ssh/**)",
    "Read(~/.aws/**)",
    "Edit(~/.aws/**)",
    "Read(~/.gnupg/**)",
    "Edit(~/.gnupg/**)",
    "Read(~/.config/gh/**)",
    "Edit(~/.config/gh/**)",
    "Read(~/.config/gcloud/**)",
    "Edit(~/.config/gcloud/**)",
    "Read(~/.kube/**)",
    "Edit(~/.kube/**)",
    "Read(~/.docker/config.json)",
    "Edit(~/.docker/config.json)",
    "Read(~/.git-credentials)",
    "Edit(~/.git-credentials)",
    "Read(~/.netrc)",
    "Edit(~/.netrc)",
    "Read(~/.pypirc)",
    "Edit(~/.pypirc)",
    // 系统配置需可读（如 /etc/gitconfig），只阻止写入
    "Edit(//etc/**)",
    "Read(**/.env)",
    "Edit(**/.env)",
    "Read(**/.env.*)",
    "Edit(**/.env.*)",
    // `!` 是 gitignore 否定，把 .env.example 从上面的拒绝范围中排除，保持模板文件可读写；
    // 它只对位于其前的相对规则生效，调整顺序时注意别让它静默失效
    "Read(!**/.env.example)",
    "Edit(!**/.env.example)",
  ],
} as const;
