export const RECOMMENDED_PERMISSION_RULES = {
  allow: [
    "Bash(pwd)",
    "Bash(date *)",
    "Bash(whoami)",
    "Bash(id)",
    "Bash(which *)",
    "Bash(file *)",
    "Bash(df *)",
    "Bash(ps *)",
    "Bash(pgrep *)",
    "Bash(lsof *)",
    "Bash(* --version)",
    "Bash(* --help *)",
    "Bash(rg *)",
    "Bash(sed *)",
    "Bash(awk *)",
    "Bash(fd *)",
    "Bash(jq *)",
    "Bash(yq *)",
    "Bash(sort *)",
    "Bash(uniq *)",
    "Bash(cut *)",
    "Bash(tr *)",
    "Bash(echo *)",
    "Bash(printf *)",
    "Bash(touch *)",
    "Bash(mkdir *)",
    "Bash(go test *)",
    "Bash(go vet *)",
    "Bash(go list *)",
    "Bash(cargo check *)",
    "Bash(cargo test *)",
    "Bash(cargo clippy *)",
    "Bash(pnpm test *)",
    "Bash(pnpm run test *)",
    "Bash(pnpm run lint *)",
    "Bash(pnpm run typecheck *)",
    "Bash(pnpm run check *)",
    "Bash(pnpm run build *)",
    "Bash(bun test *)",
    "Bash(bun run test *)",
    "Bash(bun run lint *)",
    "Bash(bun run typecheck *)",
    "Bash(bun run check *)",
    "Bash(bun run build *)",
    "Bash(make test *)",
    "Bash(make check *)",
    "Bash(make lint *)",
    "Bash(make build *)",
    "WebSearch",
    "WebFetch(domain:*)",
  ],
  ask: [
    "Bash(rm *)",
    "Bash(chmod *)",
    "Bash(chown *)",
    "Bash(kill *)",
    "Bash(killall *)",
    "Bash(pkill *)",
    "Bash(env)",
    "Bash(printenv *)",
    "Bash(cp *)",
    "Bash(mv *)",
    "Bash(open *)",
    "Bash(gh *)",
    "Bash(git commit *)",
    "Bash(git pull *)",
    "Bash(git merge *)",
    "Bash(git restore *)",
    "Bash(git checkout *)",
    "Bash(git clean *)",
    "Bash(git reset *)",
    "Bash(git rebase *)",
    "Bash(git push *)",
    "Bash(git stash *)",
    "Bash(find * -exec*)",
    "Bash(sed -i*)",
    "Bash(go run *)",
    "Bash(go get *)",
    "Bash(go install *)",
    "Bash(go generate *)",
    "Bash(go mod tidy *)",
    "Bash(cargo run *)",
    "Bash(cargo install *)",
    "Bash(cargo update *)",
    "Bash(cargo publish *)",
    "Bash(rustup *)",
    "Bash(npm *)",
    "Bash(yarn *)",
    "Bash(npx *)",
    "Bash(corepack *)",
    "Bash(curl *)",
    "Bash(wget *)",
    "Bash(pip *)",
    "Bash(python -m pip *)",
    "Bash(python *)",
    "Bash(python3 *)",
    "Bash(uv *)",
    "Bash(pnpm install *)",
    "Bash(pnpm add *)",
    "Bash(pnpm remove *)",
    "Bash(pnpm update *)",
    "Bash(pnpm dlx *)",
    "Bash(pnpm exec *)",
    "Bash(pnpm approve-builds *)",
    "Bash(bun install *)",
    "Bash(bun add *)",
    "Bash(bun remove *)",
    "Bash(bunx *)",
    "Bash(brew *)",
    "Bash(docker *)",
    "Bash(docker-compose *)",
    "Bash(rsync *)",
    "Bash(make install *)",
    "Bash(make deploy *)",
    "Bash(make release *)",
    "Bash(nc *)",
    "Bash(ncat *)",
    "Bash(telnet *)",
    "Bash(socat *)",
    "Bash(nmap *)",
    "Bash(ssh *)",
    "Bash(scp *)",
    "Bash(sftp *)",
    "Bash(kubectl *)",
    "Bash(helm *)",
    "Bash(aws *)",
    "Bash(gcloud *)",
    "Bash(az *)",
    "Bash(osascript *)",
    "Bash(launchctl *)",
    "Bash(diskutil *)",
  ],
  deny: [
    "Bash(sudo *)",
    "Bash(su *)",
    "Bash(doas *)",
    "Bash(rm -rf *)",
    "Bash(rm -fr *)",
    "Bash(rm -r -f *)",
    "Bash(rm -f -r *)",
    "Bash(rm -R *)",
    "Bash(dd *)",
    "Bash(mkfs *)",
    "Bash(shred *)",
    "Bash(diskutil erase*)",
    "Bash(diskutil partition*)",
    "Bash(chmod *777*)",
    "Bash(chmod -R 777*)",
    "Bash(shutdown *)",
    "Bash(reboot *)",
    "Bash(halt *)",
    "Bash(poweroff *)",
    "Bash(csrutil *)",
    "Bash(git push --force*)",
    "Bash(git push * --force*)",
    "Bash(git push -f *)",
    "Bash(git push * -f *)",
    "Bash(git push --mirror *)",
    "Bash(git push * --mirror *)",
    "Bash(git reset --hard*)",
    "Bash(git reset * --hard*)",
    "Bash(git clean -fd*)",
    "Bash(git clean * -fd*)",
    "Bash(git clean -fdx*)",
    "Bash(git clean -dfx*)",
    "Bash(find * -delete*)",
    "Bash(find * -exec rm*)",
    "Read(**/.env)",
    "Read(**/.env.*)",
    "Read(**/.envrc)",
    "Read(**/*.env)",
    "Read(**/secrets/**)",
    "Edit(**/secrets/**)",
    "Read(**/.secrets/**)",
    "Edit(**/.secrets/**)",
    "Read(**/*secret*.json)",
    "Edit(**/*secret*.json)",
    "Read(**/*secret*.yaml)",
    "Edit(**/*secret*.yaml)",
    "Read(**/*secret*.yml)",
    "Edit(**/*secret*.yml)",
    "Read(**/*secret*.toml)",
    "Edit(**/*secret*.toml)",
    "Read(**/*credentials*.json)",
    "Edit(**/*credentials*.json)",
    "Read(**/*credentials*.yaml)",
    "Edit(**/*credentials*.yaml)",
    "Read(**/*credentials*.yml)",
    "Edit(**/*credentials*.yml)",
    "Read(**/*credentials*.toml)",
    "Edit(**/*credentials*.toml)",
    "Read(**/*.pem)",
    "Edit(**/*.pem)",
    "Read(**/*.key)",
    "Edit(**/*.key)",
    "Read(**/*.p12)",
    "Edit(**/*.p12)",
    "Read(**/*.pfx)",
    "Edit(**/*.pfx)",
    "Read(**/id_rsa*)",
    "Edit(**/id_rsa*)",
    "Read(**/id_ed25519*)",
    "Edit(**/id_ed25519*)",
    "Read(**/.netrc)",
    "Edit(**/.netrc)",
    "Read(**/.npmrc)",
    "Edit(**/.npmrc)",
    "Read(**/.pypirc)",
    "Edit(**/.pypirc)",
    "Read(**/.docker/config.json)",
    "Edit(**/.docker/config.json)",
    "Edit(**/.git/**)",
    "Read(~/.ssh/**)",
    "Edit(~/.ssh/**)",
    "Read(~/.aws/**)",
    "Edit(~/.aws/**)",
    "Read(~/.gnupg/**)",
    "Edit(~/.gnupg/**)",
    "Read(~/.kube/**)",
    "Edit(~/.kube/**)",
    "Read(~/.docker/**)",
    "Edit(~/.docker/**)",
    "Read(//etc/**)",
    "Edit(//etc/**)",
    "Read(//root/**)",
    "Edit(//root/**)",
    "Edit(//var/**)",
  ],
} as const;
