export const RECOMMENDED_PERMISSION_RULES = {
  allow: ["WebSearch"],
  ask: [
    "Bash(rm *)",
    "Bash(kill *)",
    "Bash(killall *)",
    "Bash(pkill *)",
    "Bash(gh *)",
    "Bash(git commit *)",
    "Bash(git pull *)",
    "Bash(git merge *)",
    "Bash(git restore *)",
    "Bash(git checkout *)",
    "Bash(git clean *)",
    "Bash(git reset *)",
    "Bash(git rebase *)",
    "Bash(git push *)",
    "Bash(git stash *)",
    "Bash(cargo publish *)",
    "Bash(npm publish *)",
    "Bash(pnpm publish *)",
    "Bash(brew *)",
    "Bash(docker *)",
    "Bash(docker-compose *)",
    "Bash(make install *)",
    "Bash(make deploy *)",
    "Bash(make release *)",
    "Bash(kubectl *)",
    "Bash(helm *)",
    "Bash(aws *)",
    "Bash(gcloud *)",
    "Bash(az *)",
    "Bash(ssh *)",
    "Bash(scp *)",
    "Bash(launchctl *)",
    "Bash(diskutil *)",
  ],
  deny: [
    "Bash(sudo *)",
    "Bash(su *)",
    "Bash(doas *)",
    "Bash(rm -rf *)",
    "Bash(rm -fr *)",
    "Bash(rm -r -f *)",
    "Bash(rm -f -r *)",
    "Bash(rm -R *)",
    "Bash(rm -Rf *)",
    "Bash(rm -fR *)",
    "Bash(rm --recursive *)",
    "Bash(rm * --recursive*)",
    "Bash(/bin/rm -rf *)",
    "Bash(/bin/rm -fr *)",
    "Bash(/bin/rm -R*)",
    "Bash(command rm -rf *)",
    "Bash(command rm -fr *)",
    "Bash(dd *)",
    "Bash(mkfs *)",
    "Bash(shred *)",
    "Bash(diskutil erase*)",
    "Bash(diskutil partition*)",
    "Bash(chmod *777*)",
    "Bash(chmod -R 777*)",
    "Bash(shutdown *)",
    "Bash(reboot *)",
    "Bash(halt *)",
    "Bash(poweroff *)",
    "Bash(csrutil *)",
    "Bash(git push --force*)",
    "Bash(git push * --force*)",
    "Bash(git push -f *)",
    "Bash(git push * -f *)",
    "Bash(git push --mirror *)",
    "Bash(git push * --mirror *)",
    "Bash(git push * +*)",
    "Bash(git reset --hard*)",
    "Bash(git reset * --hard*)",
    "Bash(git clean -fd*)",
    "Bash(git clean * -fd*)",
    "Bash(git clean -fdx*)",
    "Bash(git clean -dfx*)",
    "Bash(find * -delete*)",
    "Bash(find * -exec rm*)",
    "Bash(env)",
    "Bash(printenv*)",
    "Bash(gh auth token*)",
    "Bash(gh auth status --show-token*)",
    "Bash(gh auth status -t*)",
    "Bash(aws configure get *)",
    "Bash(aws configure export-credentials*)",
    "Bash(aws sts get-session-token*)",
    "Bash(gcloud auth print-access-token*)",
    "Bash(gcloud auth print-identity-token*)",
    "Bash(gcloud auth application-default print-access-token*)",
    "Bash(kubectl config view --raw*)",
    "Bash(kubectl config view * --raw*)",
    "Bash(git credential *)",
    "Bash(security find-generic-password*)",
    "Bash(security find-internet-password*)",
    "Bash(npm token *)",
    "Read(**/.env)",
    "Read(**/.env.*)",
    "Read(**/.envrc)",
    "Read(**/*.env)",
    "Read(**/secrets/**)",
    "Edit(**/secrets/**)",
    "Read(**/.secrets/**)",
    "Edit(**/.secrets/**)",
    "Read(**/*secret*.json)",
    "Edit(**/*secret*.json)",
    "Read(**/*secret*.yaml)",
    "Edit(**/*secret*.yaml)",
    "Read(**/*secret*.yml)",
    "Edit(**/*secret*.yml)",
    "Read(**/*secret*.toml)",
    "Edit(**/*secret*.toml)",
    "Read(**/*credentials*.json)",
    "Edit(**/*credentials*.json)",
    "Read(**/*credentials*.yaml)",
    "Edit(**/*credentials*.yaml)",
    "Read(**/*credentials*.yml)",
    "Edit(**/*credentials*.yml)",
    "Read(**/*credentials*.toml)",
    "Edit(**/*credentials*.toml)",
    "Read(**/*.pem)",
    "Edit(**/*.pem)",
    "Read(**/*.key)",
    "Edit(**/*.key)",
    "Read(**/*.p12)",
    "Edit(**/*.p12)",
    "Read(**/*.pfx)",
    "Edit(**/*.pfx)",
    "Read(**/id_rsa*)",
    "Edit(**/id_rsa*)",
    "Read(**/id_ed25519*)",
    "Edit(**/id_ed25519*)",
    "Read(**/.netrc)",
    "Edit(**/.netrc)",
    "Read(**/.npmrc)",
    "Edit(**/.npmrc)",
    "Read(**/.pypirc)",
    "Edit(**/.pypirc)",
    "Read(**/.docker/config.json)",
    "Edit(**/.docker/config.json)",
    "Edit(**/.git/**)",
    "Read(~/.ssh/**)",
    "Edit(~/.ssh/**)",
    "Read(~/.aws/**)",
    "Edit(~/.aws/**)",
    "Read(~/.gnupg/**)",
    "Edit(~/.gnupg/**)",
    "Read(~/.kube/**)",
    "Edit(~/.kube/**)",
    "Read(~/.docker/**)",
    "Edit(~/.docker/**)",
    "Read(~/.config/gh/**)",
    "Edit(~/.config/gh/**)",
    "Read(~/.config/gcloud/**)",
    "Edit(~/.config/gcloud/**)",
    "Read(~/.git-credentials)",
    "Edit(~/.git-credentials)",
    // 系统配置需可读（如 /etc/gitconfig），只阻止读取系统密码和 SSH 主机私钥
    "Read(//etc/shadow)",
    "Read(//etc/gshadow)",
    "Read(//etc/ssh/ssh_host_*_key)",
    "Edit(//etc/**)",
    "Read(//root/**)",
    "Edit(//root/**)",
    "Edit(//var/**)",
  ],
} as const;
