// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getConfigWorkspace: () => typedError<ConfigWorkspace_Serialize, string>(__TAURI_INVOKE("get_config_workspace")),
	getClaudeDirectoryOverview: () => typedError<ClaudeDirectoryOverview, string>(__TAURI_INVOKE("get_claude_directory_overview")),
	getClaudeDirectoryChildren: (path: string | null) => typedError<ClaudeDirectoryListing, string>(__TAURI_INVOKE("get_claude_directory_children", { path })),
	readClaudeFilePreview: (path: string) => typedError<ClaudeFilePreview, string>(__TAURI_INVOKE("read_claude_file_preview", { path })),
	openClaudeFileInEditor: (path: string) => typedError<null, string>(__TAURI_INVOKE("open_claude_file_in_editor", { path })),
	createClaudeDirectoryEntry: (parentPath: string | null, name: string, kind: ClaudeDirectoryEntryKind) => typedError<null, string>(__TAURI_INVOKE("create_claude_directory_entry", { parentPath, name, kind })),
	renameClaudeDirectoryEntry: (path: string, newName: string) => typedError<null, string>(__TAURI_INVOKE("rename_claude_directory_entry", { path, newName })),
	deleteClaudeDirectoryEntry: (path: string) => typedError<null, string>(__TAURI_INVOKE("delete_claude_directory_entry", { path })),
	upsertProfile: (data: ProfileInput) => typedError<ConfigProfile_Serialize, string>(__TAURI_INVOKE("upsert_profile", { data })),
	duplicateProfile: (id: string, nameSuffix: string) => typedError<ConfigProfile_Serialize, string>(__TAURI_INVOKE("duplicate_profile", { id, nameSuffix })),
	reorderProfiles: (ids: string[]) => typedError<null, string>(__TAURI_INVOKE("reorder_profiles", { ids })),
	syncSharedProfileSettings: (sourceId: string, topLevelKeys: string[], envKeys: string[]) => typedError<number, string>(__TAURI_INVOKE("sync_shared_profile_settings", { sourceId, topLevelKeys, envKeys })),
	deleteProfile: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_profile", { id })),
	applyProfile: (id: string) => typedError<null, string>(__TAURI_INVOKE("apply_profile", { id })),
	importUserSettingsProfile: (data: UserSettingsImportInput) => typedError<ConfigProfile_Serialize, string>(__TAURI_INVOKE("import_user_settings_profile", { data })),
	installStatusLinePreset: (presetId: string, overwrite: boolean) => typedError<StatusLinePresetInstallResult, string>(__TAURI_INVOKE("install_status_line_preset", { presetId, overwrite })),
	previewProfile: (data: ProfileInput) => typedError<string, string>(__TAURI_INVOKE("preview_profile", { data })),
	prepareProfileLaunch: (id: string) => typedError<ProfileLaunchPayload, string>(__TAURI_INVOKE("prepare_profile_launch", { id })),
	previewProfileExport: (id: string, includeSecrets: boolean) => typedError<string, string>(__TAURI_INVOKE("preview_profile_export", { id, includeSecrets })),
	exportProfile: (id: string, targetPath: string, includeSecrets: boolean) => typedError<null, string>(__TAURI_INVOKE("export_profile", { id, targetPath, includeSecrets })),
	previewProfileImport: (sourcePath: string) => typedError<string, string>(__TAURI_INVOKE("preview_profile_import", { sourcePath })),
	importProfileFromFile: (sourcePath: string, name: string, description: string) => typedError<ConfigProfile_Serialize, string>(__TAURI_INVOKE("import_profile_from_file", { sourcePath, name, description })),
	testProfileModel: (data: ModelTestInput) => typedError<ModelTestResult_Serialize, string>(__TAURI_INVOKE("test_profile_model", { data })),
	setAppPreferences: (data: AppPreferencesInput) => typedError<AppPreferences, string>(__TAURI_INVOKE("set_app_preferences", { data })),
	/**  切换浮窗显隐（幂等）：显示时不存在则创建，隐藏时隐藏而非关闭以保留位置与状态。 */
	toggleFloatingWidget: (visible: boolean) => typedError<null, string>(__TAURI_INVOKE("toggle_floating_widget", { visible })),
	/**  浮窗点击主体：唤起主窗口并跳转到用量页。复用托盘的窗口显示逻辑，避免重复实现。 */
	openUsagePage: () => typedError<null, string>(__TAURI_INVOKE("open_usage_page")),
	getNativeOpenAppOptions: () => __TAURI_INVOKE<NativeOpenAppOptions>("get_native_open_app_options"),
	getMemories: () => typedError<MemoryState_Serialize, string>(__TAURI_INVOKE("get_memories")),
	addMemory: (data: MemoryData) => typedError<MemoryState_Serialize, string>(__TAURI_INVOKE("add_memory", { data })),
	applyMemoryPreset: (data: MemoryPresetApplyInput) => typedError<MemoryPresetApplyResult_Serialize, string>(__TAURI_INVOKE("apply_memory_preset", { data })),
	getMemoryPresetContent: (data: MemoryPresetContentInput) => typedError<MemoryPresetContentResult, string>(__TAURI_INVOKE("get_memory_preset_content", { data })),
	updateMemory: (id: string, data: MemoryData) => typedError<MemoryState_Serialize, string>(__TAURI_INVOKE("update_memory", { id, data })),
	duplicateMemory: (id: string, nameSuffix: string) => typedError<MemoryState_Serialize, string>(__TAURI_INVOKE("duplicate_memory", { id, nameSuffix })),
	previewDeleteMemory: (id: string) => typedError<MemoryDeletePreview, string>(__TAURI_INVOKE("preview_delete_memory", { id })),
	deleteMemory: (id: string) => typedError<MemoryState_Serialize, string>(__TAURI_INVOKE("delete_memory", { id })),
	toggleMemory: (id: string) => typedError<MemoryState_Serialize, string>(__TAURI_INVOKE("toggle_memory", { id })),
	importUnmanagedMemory: (source: UnmanagedMemorySource) => typedError<MemoryState_Serialize, string>(__TAURI_INVOKE("import_unmanaged_memory", { source })),
	importMemoriesFromDirectory: (sourceDir: string) => typedError<MemoryDirectoryImportResult_Serialize, string>(__TAURI_INVOKE("import_memories_from_directory", { sourceDir })),
	/**  获取当前统计数据 */
	getStats: () => typedError<ClaudeStats, string>(__TAURI_INVOKE("get_stats")),
	/**  用默认编辑器打开 ~/.claude.json */
	openClaudeJsonInEditor: () => typedError<null, string>(__TAURI_INVOKE("open_claude_json_in_editor")),
	/**  读取历史记录文件，返回内容和 mtime；文件不存在时返回空内容 */
	getHistory: () => typedError<HistoryResult, string>(__TAURI_INVOKE("get_history")),
	/**  仅当文件有变化时返回新内容，否则返回 None */
	getHistoryIfChanged: (lastMtime: number) => typedError<{
	content: string,
	mtime: number,
} | null, string>(__TAURI_INVOKE("get_history_if_changed", { lastMtime })),
	/**  获取指定 session 的完整对话记录 */
	getSessionDetail: (project: string, sessionId: string) => typedError<SessionDetail, string>(__TAURI_INVOKE("get_session_detail", { project, sessionId })),
	openSessionFileInEditor: (project: string, sessionId: string) => typedError<null, string>(__TAURI_INVOKE("open_session_file_in_editor", { project, sessionId })),
	/**  读取会话关联 plan 文件的实时内容,供应用内预览 */
	readSessionPlan: (project: string, sessionId: string) => typedError<SessionPlan, string>(__TAURI_INVOKE("read_session_plan", { project, sessionId })),
	/**  用默认编辑器打开会话关联的 plan 文件 */
	openSessionPlanInEditor: (project: string, sessionId: string) => typedError<null, string>(__TAURI_INVOKE("open_session_plan_in_editor", { project, sessionId })),
	getAppLogs: (query: {
	level?: LogLevel | null,
	search?: string | null,
	limit?: number | null,
} | null) => typedError<LogView_Serialize, string>(__TAURI_INVOKE("get_app_logs", { query })),
	openLogsDir: () => typedError<null, string>(__TAURI_INVOKE("open_logs_dir")),
	clearAppLogs: () => typedError<LogView_Serialize, string>(__TAURI_INVOKE("clear_app_logs")),
	getProjectDetail: (project: string) => typedError<ProjectDetail_Serialize, string>(__TAURI_INVOKE("get_project_detail", { project })),
	getProjectClaudeDirectoryOverview: (project: string) => typedError<ClaudeDirectoryOverview, string>(__TAURI_INVOKE("get_project_claude_directory_overview", { project })),
	getProjectClaudeFilePreview: (project: string, relativePath: string) => typedError<ClaudeFilePreview, string>(__TAURI_INVOKE("get_project_claude_file_preview", { project, relativePath })),
	createProjectClaudeSettingsFile: (project: string, scope: ProjectClaudeSettingsScope) => typedError<null, string>(__TAURI_INVOKE("create_project_claude_settings_file", { project, scope })),
	openProjectClaudeFileInEditor: (project: string, relativePath: string) => typedError<null, string>(__TAURI_INVOKE("open_project_claude_file_in_editor", { project, relativePath })),
	createProjectAgentsSkillsSymlink: (project: string) => typedError<null, string>(__TAURI_INVOKE("create_project_agents_skills_symlink", { project })),
	createProjectAgentsSymlink: (project: string) => typedError<null, string>(__TAURI_INVOKE("create_project_agents_symlink", { project })),
	openProjectInTerminal: (project: string) => typedError<null, string>(__TAURI_INVOKE("open_project_in_terminal", { project })),
	openProjectInEditor: (project: string) => typedError<null, string>(__TAURI_INVOKE("open_project_in_editor", { project })),
	previewProjectLocalDataPurge: (project: string) => typedError<ProjectPurgeOutput, string>(__TAURI_INVOKE("preview_project_local_data_purge", { project })),
	purgeProjectLocalData: (project: string) => typedError<ProjectPurgeOutput, string>(__TAURI_INVOKE("purge_project_local_data", { project })),
	previewProjectBranchCleanup: (project: string) => typedError<ProjectGitCleanupPreview_Serialize, string>(__TAURI_INVOKE("preview_project_branch_cleanup", { project })),
	cleanupProjectBranches: (project: string, branches: string[]) => typedError<ProjectGitCleanupResult, string>(__TAURI_INVOKE("cleanup_project_branches", { project, branches })),
	previewProjectWorktreeCleanup: (project: string) => typedError<ProjectGitCleanupPreview_Serialize, string>(__TAURI_INVOKE("preview_project_worktree_cleanup", { project })),
	cleanupProjectWorktrees: (project: string, worktrees: string[]) => typedError<ProjectGitCleanupResult, string>(__TAURI_INVOKE("cleanup_project_worktrees", { project, worktrees })),
	getProjectAutoMemoryStatus: (project: string, repoRoot: string | null) => typedError<ProjectAutoMemoryStatus, string>(__TAURI_INVOKE("get_project_auto_memory_status", { project, repoRoot })),
	getProjectAutoMemoryOverview: (project: string, repoRoot: string | null) => typedError<ClaudeDirectoryOverview, string>(__TAURI_INVOKE("get_project_auto_memory_overview", { project, repoRoot })),
	readProjectAutoMemoryFile: (project: string, repoRoot: string | null, relativePath: string) => typedError<ClaudeFilePreview, string>(__TAURI_INVOKE("read_project_auto_memory_file", { project, repoRoot, relativePath })),
	deleteProjectAutoMemoryEntry: (project: string, repoRoot: string | null, relativePath: string) => typedError<null, string>(__TAURI_INVOKE("delete_project_auto_memory_entry", { project, repoRoot, relativePath })),
	openProjectAutoMemoryFileInEditor: (project: string, repoRoot: string | null, relativePath: string) => typedError<null, string>(__TAURI_INVOKE("open_project_auto_memory_file_in_editor", { project, repoRoot, relativePath })),
	/**  获取所有 Skills（启用 + 禁用） */
	getSkills: () => typedError<Skill[], string>(__TAURI_INVOKE("get_skills")),
	addSkill: (data: SkillData) => typedError<Skill, string>(__TAURI_INVOKE("add_skill", { data })),
	updateSkill: (id: string, isActive: boolean, data: SkillData) => typedError<Skill, string>(__TAURI_INVOKE("update_skill", { id, isActive, data })),
	duplicateSkill: (id: string, isActive: boolean, nameSuffix: string) => typedError<Skill, string>(__TAURI_INVOKE("duplicate_skill", { id, isActive, nameSuffix })),
	deleteSkill: (id: string, isActive: boolean) => typedError<null, string>(__TAURI_INVOKE("delete_skill", { id, isActive })),
	/**  切换 Skill 的启用/禁用状态 */
	toggleSkill: (id: string, isActive: boolean) => typedError<Skill, string>(__TAURI_INVOKE("toggle_skill", { id, isActive })),
	getSkillFileTree: (id: string, isActive: boolean) => typedError<SkillFileTreeEntry[], string>(__TAURI_INVOKE("get_skill_file_tree", { id, isActive })),
	openSkillInEditor: (id: string, isActive: boolean) => typedError<null, string>(__TAURI_INVOKE("open_skill_in_editor", { id, isActive })),
	importSkillsFromDirectory: (sourceDir: string) => typedError<SkillDirectoryImportResult, string>(__TAURI_INVOKE("import_skills_from_directory", { sourceDir })),
	syncSkillToCodex: (id: string, isActive: boolean) => typedError<null, string>(__TAURI_INVOKE("sync_skill_to_codex", { id, isActive })),
	getUsageSnapshot: (filter: UsageFilter, granularity: UsageTimeGranularity) => typedError<UsageSnapshot, string>(__TAURI_INVOKE("get_usage_snapshot", { filter, granularity })),
	getSessionUsageDetail: (sessionId: string) => typedError<SessionUsageDetail, string>(__TAURI_INVOKE("get_session_usage_detail", { sessionId })),
	refreshUsagePricing: () => typedError<PricingTable, string>(__TAURI_INVOKE("refresh_usage_pricing")),
	rescanUsage: () => typedError<ScanResult, string>(__TAURI_INVOKE("rescan_usage")),
	/**
	 *  触发 claude 读取插件目录缓存，按其默认 24h TTL 策略刷新安装数。
	 *
	 *  不主动删缓存、不强制刷新：执行 `claude plugin list --available --json`，claude 内部若发现
	 *  本地 `~/.claude/plugins/plugin-catalog-cache.json` 超过 24h TTL 会自动从远端重拉并重写，未过期
	 *  则沿用缓存。安装数（`unique_installs`）即来自该缓存的 catalog。注意 `claude plugin marketplace
	 *  update` 只更新 marketplace 克隆、不碰该缓存，刷不了安装数。返回 `Result<(), String>`：前端只需
	 *  成功/失败，CLI 原始输出仅进后端日志。
	 */
	refreshPluginInstallCounts: () => typedError<null, string>(__TAURI_INVOKE("refresh_plugin_install_counts")),
	/**  探测 ANTICATER 设备是否连接(设置页显式调用)。 */
	ledProbeStatus: () => __TAURI_INVOKE<LedProbeStatus>("led_probe_status"),
	/**  测试某个灯效(设置页「测试」按钮 / 真机验证门)。立即下发,不受 enabled 影响。 */
	ledTestMode: (mode: number) => typedError<null, string>(__TAURI_INVOKE("led_test_mode", { mode })),
	/**  设置页"试听"入口：立即播放一次选中音效。 */
	previewWaitingSound: (sound: WaitingSound) => typedError<null, string>(__TAURI_INVOKE("preview_waiting_sound", { sound })),
};

/* Types */
export type ActiveUserSettingsMismatch = {
	profileId: string,
	sourcePath: string,
	expectedSettings: unknown,
	actualSettings: unknown,
};

export type AgentsStatus = "missing" | "correctSymlink" | "wrongSymlink" | "plainFileConflict";

export type AppPreferences = {
	showTrayTitle?: boolean,
	showTraySessions?: boolean,
	systemNotificationsEnabled?: boolean,
	collapseSidebarByDefault?: boolean,
	thirdPartyProviderPricingEnabled?: boolean,
	uiLanguage?: string,
	defaultTerminalApp?: string,
	defaultEditorApp?: string | null,
	trayTitleMaxChars?: number | null,
	sessionTrayCountStyle?: SessionTrayCountStyle,
	trayPulseWaiting?: boolean,
	focusSessionShortcut?: string | null,
	ledControl?: LedControlPreferences,
	/**  桌面用量浮窗是否启用（置顶半透明小窗，实时展示今日用量）。 */
	floatingWidgetEnabled?: boolean,
	/**  浮窗展示的指标 key 列表，顺序即展示顺序，取值见 WIDGET_METRIC_KEYS。 */
	floatingWidgetMetrics?: string[],
	/**  浮窗面板不透明度百分比，范围 30-100（前端按 /100 映射到 CSS opacity）。 */
	floatingWidgetOpacity?: number,
	/**  会话等待输入时是否播放提示音效（独立于 system_notifications_enabled）。 */
	waitingSoundEnabled?: boolean,
	/**  等待提示音效，默认 Glass。 */
	waitingSound?: WaitingSound,
};

export type AppPreferencesInput = {
	showTrayTitle: boolean,
	showTraySessions: boolean,
	systemNotificationsEnabled?: boolean,
	collapseSidebarByDefault?: boolean,
	thirdPartyProviderPricingEnabled?: boolean,
	uiLanguage: string,
	defaultTerminalApp: string,
	defaultEditorApp: string | null,
	trayTitleMaxChars?: number | null,
	sessionTrayCountStyle?: SessionTrayCountStyle,
	trayPulseWaiting?: boolean,
	focusSessionShortcut?: string | null,
	ledControl?: LedControlPreferences,
	floatingWidgetEnabled?: boolean,
	floatingWidgetMetrics?: string[],
	floatingWidgetOpacity?: number,
	waitingSoundEnabled?: boolean,
	waitingSound?: WaitingSound,
};

export type BindingState = BindingState_Serialize | BindingState_Deserialize;

export type BindingState_Deserialize = {
	userProfileId: string | null,
	userLastAppliedAt: string | null,
};

export type BindingState_Serialize = {
	userProfileId?: string | null,
	userLastAppliedAt?: string | null,
};

export type ClaudeDirectoryEntry = {
	path: string,
	name: string,
	kind: ClaudeDirectoryEntryKind,
	size: number,
	modifiedAt: number,
};

export type ClaudeDirectoryEntryKind = "file" | "directory";

export type ClaudeDirectoryListing = {
	rootPath: string,
	parentPath: string | null,
	maxEntries: number,
	entries: ClaudeDirectoryEntry[],
	truncated: boolean,
	reachedEntryLimit: boolean,
	skippedSymlinkCount: number,
};

export type ClaudeDirectoryOverview = {
	rootPath: string,
	maxEntries: number,
	maxDepth: number,
	entries: ClaudeDirectoryEntry[],
	truncated: boolean,
	reachedEntryLimit: boolean,
	reachedDepthLimit: boolean,
	skippedSymlinkCount: number,
	skippedNodeModulesCount: number,
};

export type ClaudeFilePreview = {
	path: string,
	name: string,
	content: string,
	isBinary: boolean,
	truncated: boolean,
	size: number,
	modifiedAt: number,
	encoding: string,
};

/**  从 ~/.claude.json 解析的完整统计数据 */
export type ClaudeStats = {
	numStartups?: number,
	firstStartTime?: string | null,
	projects?: { [key in string]: ProjectStats },
	toolUsage?: { [key in string]: UsageEntry },
	skillUsage?: { [key in string]: UsageEntry },
	lastPlanModeUse?: number | null,
	btwUseCount?: number | null,
};

export type ConfigProfile = ConfigProfile_Serialize | ConfigProfile_Deserialize;

export type ConfigProfile_Deserialize = {
	id: string,
	name: string,
	description: string,
	settings: unknown,
	createdAt: string,
	updatedAt: string,
} & {
	providerId: string | null,
};

export type ConfigProfile_Serialize = {
	id: string,
	name: string,
	description: string,
	providerId?: string | null,
	settings: unknown,
	createdAt: string,
	updatedAt: string,
};

export type ConfigWorkspace = ConfigWorkspace_Serialize | ConfigWorkspace_Deserialize;

export type ConfigWorkspace_Deserialize = {
	app: AppPreferences,
	builtinProviders: Provider_Deserialize[],
	profiles: ConfigProfile_Deserialize[],
	bindings: BindingState_Deserialize,
	unmanagedUserSettings: UnmanagedUserSettings_Deserialize | null,
	activeUserSettingsMismatch: ActiveUserSettingsMismatch | null,
};

export type ConfigWorkspace_Serialize = {
	app: AppPreferences,
	builtinProviders: Provider_Serialize[],
	profiles: ConfigProfile_Serialize[],
	bindings: BindingState_Serialize,
	unmanagedUserSettings?: UnmanagedUserSettings_Serialize | null,
	activeUserSettingsMismatch?: ActiveUserSettingsMismatch | null,
};

export type DailyUsage = {
	date: string,
	messages: number,
	sessions: number,
	inputTokens: number,
	outputTokens: number,
	cacheCreationTokens: number,
	cacheReadTokens: number,
	cost: number | null,
	byModel: ModelUsageStat[],
};

/**  历史记录读取结果 */
export type HistoryResult = {
	content: string,
	mtime: number,
};

/**  单个 hook 调用：命令与耗时（耗时可能缺省） */
export type HookCall = {
	command: string,
	duration_ms: number | null,
};

/**  「会话状态 → 灯效」映射偏好,作为 `AppPreferences.led_control` 持久化。 */
export type LedControlPreferences = {
	/**  是否启用 LED 联动(默认关,opt-in)。关闭时不主动驱动设备。 */
	enabled?: boolean,
	/**  等待输入时的灯效模式(默认 5 闪烁)。 */
	waitingMode?: number,
	/**  工作中时的灯效模式(默认 1 顺时针)。 */
	runningMode?: number,
	/**  已完成/空闲时的灯效模式(默认 2 逆时针)。 */
	idleMode?: number,
};

/**  设备连接探测结果,供设置页展示。 */
export type LedProbeStatus = {
	connected: boolean,
};

export type LocalizedText = {
	zh: string,
	en: string,
};

export type LogEntry = LogEntry_Serialize | LogEntry_Deserialize;

export type LogEntry_Deserialize = {
	timestamp: string | null,
	level: LogLevel,
	target: string | null,
	message: string,
	raw: string,
};

export type LogEntry_Serialize = {
	timestamp?: string | null,
	level: LogLevel,
	target?: string | null,
	message: string,
	raw: string,
};

export type LogLevel = "error" | "warn" | "info" | "debug" | "trace" | "unknown";

export type LogQuery = {
	level?: LogLevel | null,
	search?: string | null,
	limit?: number | null,
};

export type LogView = LogView_Serialize | LogView_Deserialize;

export type LogView_Deserialize = {
	logDir: string,
	entries: LogEntry_Deserialize[],
	truncated: boolean,
};

export type LogView_Serialize = {
	logDir: string,
	entries: LogEntry_Serialize[],
	truncated: boolean,
};

export type Memory = Memory_Serialize | Memory_Deserialize;

/**  新增/更新记忆的数据传输对象 */
export type MemoryData = {
	id: string | null,
	name: string,
	content: string,
	targetType: MemoryTargetType,
	rulePath: string | null,
	pathPatterns?: string[],
};

export type MemoryDeletePreview = {
	cleanupDirs: string[],
};

export type MemoryDirectoryImportItem = MemoryDirectoryImportItem_Serialize | MemoryDirectoryImportItem_Deserialize;

export type MemoryDirectoryImportItem_Deserialize = {
	sourcePath: string,
	name: string,
	targetType: MemoryTargetType,
	rulePath: string | null,
};

export type MemoryDirectoryImportItem_Serialize = {
	sourcePath: string,
	name: string,
	targetType: MemoryTargetType,
	rulePath?: string | null,
};

export type MemoryDirectoryImportResult = MemoryDirectoryImportResult_Serialize | MemoryDirectoryImportResult_Deserialize;

export type MemoryDirectoryImportResult_Deserialize = {
	state: MemoryState_Deserialize,
	imported: MemoryDirectoryImportItem_Deserialize[],
	skipped: MemoryDirectoryImportSkippedItem_Deserialize[],
};

export type MemoryDirectoryImportResult_Serialize = {
	state: MemoryState_Serialize,
	imported: MemoryDirectoryImportItem_Serialize[],
	skipped: MemoryDirectoryImportSkippedItem_Serialize[],
};

export type MemoryDirectoryImportSkipReason = "duplicateClaude" | "duplicateRulePath" | "unsupportedSymlink" | "invalidRulePath" | "readError";

export type MemoryDirectoryImportSkippedItem = MemoryDirectoryImportSkippedItem_Serialize | MemoryDirectoryImportSkippedItem_Deserialize;

export type MemoryDirectoryImportSkippedItem_Deserialize = {
	sourcePath: string,
	reason: MemoryDirectoryImportSkipReason,
	detail: string | null,
};

export type MemoryDirectoryImportSkippedItem_Serialize = {
	sourcePath: string,
	reason: MemoryDirectoryImportSkipReason,
	detail?: string | null,
};

export type MemoryPresetAction = "createClaude";

export type MemoryPresetApplyInput = {
	presetId: string,
	language: MemoryPresetLanguage,
	action: MemoryPresetAction,
};

export type MemoryPresetApplyOutcome = "createdClaude" | "activatedExisting";

export type MemoryPresetApplyResult = MemoryPresetApplyResult_Serialize | MemoryPresetApplyResult_Deserialize;

export type MemoryPresetApplyResult_Deserialize = {
	state: MemoryState_Deserialize,
	outcome: MemoryPresetApplyOutcome,
	memoryId: string,
};

export type MemoryPresetApplyResult_Serialize = {
	state: MemoryState_Serialize,
	outcome: MemoryPresetApplyOutcome,
	memoryId: string,
};

export type MemoryPresetContentInput = {
	presetId: string,
	language: MemoryPresetLanguage,
};

export type MemoryPresetContentResult = {
	presetId: string,
	language: MemoryPresetLanguage,
	name: string,
	content: string,
	sourceUrl: string,
};

export type MemoryPresetLanguage = "zh" | "en";

export type MemoryState = MemoryState_Serialize | MemoryState_Deserialize;

export type MemoryState_Deserialize = {
	version?: number,
	memories?: Memory_Deserialize[],
	unmanagedMemories?: UnmanagedMemory[],
};

export type MemoryState_Serialize = {
	version: number,
	memories: Memory_Serialize[],
	unmanagedMemories?: UnmanagedMemory[],
};

export type MemoryTargetType = "claude" | "rule";

export type Memory_Deserialize = {
	id: string,
	name: string,
	content: string,
	targetType: MemoryTargetType,
	rulePath: string | null,
	pathPatterns?: string[],
	isActive: boolean,
	createdAt: number,
	updatedAt: number,
};

export type Memory_Serialize = {
	id: string,
	name: string,
	content: string,
	targetType: MemoryTargetType,
	rulePath: string | null,
	pathPatterns?: string[],
	isActive: boolean,
	createdAt: number,
	updatedAt: number,
};

/**  对话消息内容块 */
export type MessageBlock =
/**  文本内容 */
{ type: "text"; text: string } |
/**  思考过程 */
{ type: "thinking"; thinking: string } |
/**  工具调用 */
{ type: "tool_use"; name: string; input_preview: string } |
/**  工具返回结果 */
{ type: "tool_result"; content: string } |
/**  斜杠命令 */
{ type: "command"; name: string; args: string | null } |
/**  系统信息 */
{ type: "system"; summary: string } |
/**  图片内容 */
{ type: "image"; source_type: string; media_type: string; data: string | null } |
/**  计划内容（用户审批的 plan） */
{ type: "plan"; summary: string; content: string } |
/**  hook 触发记录（hookInfos / hookErrors / preventedContinuation / stopReason） */
{ type: "hook"; hooks: HookCall[]; errors: string[]; prevented_continuation: boolean; stop_reason: string | null } |
/**  模式切换（plan / default 等） */
{ type: "mode_change"; mode: string } |
/**  进入 plan 模式（来自 plan_mode attachment） */
{ type: "plan_mode_entered"; plan_file_path: string | null } |
/**  退出 plan 模式 / 提交计划（来自 ExitPlanMode tool_use） */
{ type: "plan_mode_exited"; plan_file_path: string | null };

/**  单模型价格（per million tokens） */
export type ModelPrice = {
	input?: number | null,
	output?: number | null,
	cache_read?: number | null,
	cache_write?: number | null,
};

export type ModelTestInput = {
	id: string | null,
	name: string,
	description: string,
	providerId: string | null,
	settings: unknown,
	promptText?: string | null,
};

export type ModelTestResult = ModelTestResult_Serialize | ModelTestResult_Deserialize;

export type ModelTestResult_Deserialize = {
	ok: boolean,
	responseText: string,
	promptText: string,
	resolvedModel: string,
	providerModel: string | null,
	durationMs: number,
	requestId: string | null,
	stopReason: string | null,
	statusCode: number | null,
	errorMessage: string | null,
	requestMethod: string,
	requestUrl: string,
	requestHeaders: { [key in string]: string },
	requestBody: string,
	responseHeaders: { [key in string]: string },
	rawResponse: string | null,
};

export type ModelTestResult_Serialize = {
	ok: boolean,
	responseText: string,
	promptText: string,
	resolvedModel: string,
	providerModel?: string | null,
	durationMs: number,
	requestId?: string | null,
	stopReason?: string | null,
	statusCode?: number | null,
	errorMessage?: string | null,
	requestMethod: string,
	requestUrl: string,
	requestHeaders: { [key in string]: string },
	requestBody: string,
	responseHeaders: { [key in string]: string },
	rawResponse?: string | null,
};

/**  单个模型的使用明细 */
export type ModelUsageEntry = {
	inputTokens?: number,
	outputTokens?: number,
	cacheReadInputTokens?: number,
	cacheCreationInputTokens?: number,
	webSearchRequests?: number,
	costUsd?: number | null,
};

export type ModelUsageStat = {
	model: string,
	messages: number,
	inputTokens: number,
	outputTokens: number,
	cacheCreationTokens: number,
	cacheReadTokens: number,
	cost: number | null,
};

export type NativeOpenAppOption = {
	slug: string,
	label: string,
};

export type NativeOpenAppOptions = {
	platform: NativePlatform,
	supportedEditors: NativeOpenAppOption[],
	supportedTerminals: NativeOpenAppOption[],
	editors: NativeOpenAppOption[],
	terminals: NativeOpenAppOption[],
};

export type NativePlatform = "macos" | "linux" | "windows" | "other";

/**  两端配对的整体状态，覆盖 CLAUDE.md ↔ AGENTS.md 与 `.claude/skills` ↔ `.agents/skills` */
export type PairStatus =
/**  两端都不存在 */
"bothMissing" |
/**  仅 Claude 端为真文件 / 真目录，可派生 Codex 端软链 */
"onlyClaude" |
/**  仅 Codex 端为真文件 / 真目录，可派生 Claude 端软链 */
"onlyAgents" |
/**  已成对（hard link / 内容相同 / 软链方向正确） */
"paired" |
/**  一端是真源，另一端是错误软链，可删除旧软链后重建 */
"wrongSymlink" |
/**  两端都是真文件且无法判源（内容不同或互不相关） */
"conflict" |
/**  两端都是软链，或仅有孤儿软链而无真源，无法修复 */
"orphanSymlink";

/**  价格表来源 */
export type PricingSource = "builtin" | "cache" | "network";

/**  完整价格表 */
export type PricingTable = {
	source: PricingSource,
	fetchedAtMs: number | null,
	models: { [key in string]: ModelPrice },
};

export type ProfileInput = {
	id: string | null,
	name: string,
	description: string,
	providerId: string | null,
	settings: unknown,
};

/**  多配置启动命令的返回载荷：配置文件绝对路径 + 仅含 env 的紧凑 JSON。 */
export type ProfileLaunchPayload = {
	/**  写入磁盘的完整 settings 文件绝对路径，供 `claude --settings "<path>"` 使用。 */
	settingsPath: string,
	/**  仅含 env 块的紧凑单行 JSON，供 `claude --settings '<json>'` 内联使用。 */
	envOnlyJson: string,
};

export type ProjectAutoMemoryStatus = {
	/**  `autoMemoryEnabled`（默认开启）；缺省即视为启用。 */
	enabled: boolean,
	/**  设置里的 `autoMemoryDirectory` 原始值（绝对或 `~/` 开头）；未自定义为 None。 */
	directoryOverride: string | null,
	/**  解析后的 memory 目录是否位于 ~/.claude 内；为 false 时不提供应用内浏览。 */
	isInsideClaudeDir: boolean,
	/**  memory 目录是否存在。 */
	exists: boolean,
	/**  memory 目录内的文件数（递归，不含目录条目）。 */
	memoryFileCount: number,
	/**  解析后的 memory 目录展示路径。 */
	resolvedDirLabel: string,
};

export type ProjectBranch = ProjectBranch_Serialize | ProjectBranch_Deserialize;

export type ProjectBranchCleanupCandidate = ProjectBranchCleanupCandidate_Serialize | ProjectBranchCleanupCandidate_Deserialize;

export type ProjectBranchCleanupCandidate_Deserialize = {
	name: string,
	reason: ProjectGitCleanupReason,
	forceDelete: boolean,
	lastCommitAt: number | null,
	lastCommitSubject: string | null,
};

export type ProjectBranchCleanupCandidate_Serialize = {
	name: string,
	reason: ProjectGitCleanupReason,
	forceDelete: boolean,
	lastCommitAt?: number | null,
	lastCommitSubject?: string | null,
};

export type ProjectBranch_Deserialize = {
	name: string,
	isCurrent: boolean,
	lastCommitAt: number | null,
	lastCommitSubject: string | null,
};

export type ProjectBranch_Serialize = {
	name: string,
	isCurrent: boolean,
	lastCommitAt?: number | null,
	lastCommitSubject?: string | null,
};

/**  项目级 settings 文件的归属（共享 vs 本地覆盖） */
export type ProjectClaudeSettingsScope = "shared" | "local";

export type ProjectDetail = ProjectDetail_Serialize | ProjectDetail_Deserialize;

export type ProjectDetail_Deserialize = {
	path: string,
	shortName: string,
	exists: boolean,
	isGitRepo: boolean,
	repoRoot: string | null,
	repositoryUrl: string | null,
	hasClaudeMd: boolean,
	hasProjectClaudeDir: boolean,
	hasProjectClaudeSkills: boolean,
	hasProjectClaudeSettings: boolean,
	hasProjectClaudeSettingsLocal: boolean,
	projectClaudeRulesCount: number,
	agentsStatus: AgentsStatus,
	agentsSkillsStatus: AgentsStatus,
	memoryPairStatus: PairStatus,
	skillsPairStatus: PairStatus,
	projectSkills: ProjectSkillSummary[],
	branches: ProjectBranch_Deserialize[],
	worktrees: ProjectWorktree_Deserialize[],
};

export type ProjectDetail_Serialize = {
	path: string,
	shortName: string,
	exists: boolean,
	isGitRepo: boolean,
	repoRoot?: string | null,
	repositoryUrl?: string | null,
	hasClaudeMd: boolean,
	hasProjectClaudeDir: boolean,
	hasProjectClaudeSkills: boolean,
	hasProjectClaudeSettings: boolean,
	hasProjectClaudeSettingsLocal: boolean,
	projectClaudeRulesCount: number,
	agentsStatus: AgentsStatus,
	agentsSkillsStatus: AgentsStatus,
	memoryPairStatus: PairStatus,
	skillsPairStatus: PairStatus,
	projectSkills: ProjectSkillSummary[],
	branches: ProjectBranch_Serialize[],
	worktrees: ProjectWorktree_Serialize[],
};

export type ProjectGitCleanupPreview = ProjectGitCleanupPreview_Serialize | ProjectGitCleanupPreview_Deserialize;

export type ProjectGitCleanupPreview_Deserialize = {
	project: string,
	repoRoot: string | null,
	baseBranch: string | null,
	branchCandidates: ProjectBranchCleanupCandidate_Deserialize[],
	worktreeCandidates: ProjectWorktreeCleanupCandidate_Deserialize[],
};

export type ProjectGitCleanupPreview_Serialize = {
	project: string,
	repoRoot?: string | null,
	baseBranch?: string | null,
	branchCandidates: ProjectBranchCleanupCandidate_Serialize[],
	worktreeCandidates: ProjectWorktreeCleanupCandidate_Serialize[],
};

export type ProjectGitCleanupReason = "merged" | "upstreamGone";

export type ProjectGitCleanupResult = {
	project: string,
	deletedBranches: string[],
	deletedWorktrees: string[],
	errors: string[],
};

export type ProjectOption = {
	projectPath: string,
	projectDir: string,
};

export type ProjectPurgeOutput = {
	project: string,
	output: string,
};

export type ProjectSkillSummary = {
	id: string,
	isSymlink: boolean,
};

/**  项目级统计 */
export type ProjectStats = {
	lastCost?: number | null,
	lastDuration?: number,
	lastSessionId?: string | null,
	lastSessionMetrics?: SessionMetrics | null,
	lastTotalInputTokens?: number,
	lastTotalOutputTokens?: number,
	lastTotalCacheCreationInputTokens?: number,
	lastTotalCacheReadInputTokens?: number,
	lastSessionModified?: number,
	lastLinesAdded?: number,
	lastLinesRemoved?: number,
	lastTotalWebSearchRequests?: number,
	lastModelUsage?: { [key in string]: ModelUsageEntry } | null,
	lastSessionFirstPrompt?: string | null,
};

export type ProjectUsage = {
	projectPath: string,
	projectDir: string,
	sessions: number,
	messages: number,
	lastActiveMs: number,
	inputTokens: number,
	outputTokens: number,
	cacheCreationTokens: number,
	cacheReadTokens: number,
	cost: number | null,
	byModel: ModelUsageStat[],
};

export type ProjectWorktree = ProjectWorktree_Serialize | ProjectWorktree_Deserialize;

export type ProjectWorktreeCleanupCandidate = ProjectWorktreeCleanupCandidate_Serialize | ProjectWorktreeCleanupCandidate_Deserialize;

export type ProjectWorktreeCleanupCandidate_Deserialize = {
	path: string,
	branch: string | null,
	head: string | null,
	reason: ProjectGitCleanupReason,
	isDetached: boolean,
};

export type ProjectWorktreeCleanupCandidate_Serialize = {
	path: string,
	branch?: string | null,
	head?: string | null,
	reason: ProjectGitCleanupReason,
	isDetached: boolean,
};

export type ProjectWorktree_Deserialize = {
	path: string,
	branch: string | null,
	head: string | null,
	isCurrent: boolean,
	isDetached: boolean,
};

export type ProjectWorktree_Serialize = {
	path: string,
	branch?: string | null,
	head?: string | null,
	isCurrent: boolean,
	isDetached: boolean,
};

export type Provider = Provider_Serialize | Provider_Deserialize;

export type ProviderModel = {
	id: string,
};

export type Provider_Deserialize = {
	id: string,
	name: string,
	localizedName: LocalizedText | null,
	description: string,
	docUrl: string | null,
	models: ProviderModel[] | null,
	modelSuggestions?: string[],
	env?: { [key in string]: string },
};

export type Provider_Serialize = {
	id: string,
	name: string,
	localizedName?: LocalizedText | null,
	description: string,
	docUrl?: string | null,
	models?: ProviderModel[] | null,
	modelSuggestions: string[],
	env: { [key in string]: string },
};

export type ScanResult = {
	filesScanned: number,
	newRecords: number,
	elapsedMs: number,
};

/**  会话详情返回结果 */
export type SessionDetail = {
	session_id: string,
	project: string,
	messages: SessionMessage[],
	/**  harness 注入且实际存在的关联 plan 文件绝对路径,无关联时为 None */
	plan_file_path: string | null,
	/**  按 agentId 聚合的 subagent 侧链子时间线 */
	subagents: SubagentChain[],
};

/**  一条对话消息 */
export type SessionMessage = {
	role: string,
	blocks: MessageBlock[],
	timestamp: string | null,
};

/**  会话性能指标 */
export type SessionMetrics = {
	frame_duration_ms_avg?: number | null,
	frame_duration_ms_p95?: number | null,
	hook_duration_ms_avg?: number | null,
	hook_duration_ms_p95?: number | null,
	hook_duration_ms_count?: number | null,
	pre_tool_hook_duration_ms_avg?: number | null,
	pre_tool_hook_duration_ms_p95?: number | null,
};

/**  会话关联 plan 内容 */
export type SessionPlan = {
	path: string,
	content: string,
};

/**
 *  会话托盘计数数字的展示风格。
 *  纯文本菜单栏无法做图层角标，用 Unicode 上标数字模拟"右上角角标"。
 */
export type SessionTrayCountStyle =
/**  普通数字，空格分隔：`🔴 1 🟢 1 ⚪ 2` */
"plain" |
/**  上标数字紧贴 emoji，类别空格分隔：`🔴¹ 🟢¹ ⚪²` */
"superscript" |
/**  上标数字 + 无类别空格，最省宽度：`🔴¹🟢¹⚪²` */
"superscriptCompact";

export type SessionUsage = {
	sessionId: string,
	projectPath: string,
	projectDir: string,
	startedAtMs: number,
	lastActiveMs: number,
	messages: number,
	models: string[],
	inputTokens: number,
	outputTokens: number,
	cacheCreationTokens: number,
	cacheReadTokens: number,
	cost: number | null,
};

export type SessionUsageDetail = {
	session: SessionUsage,
	messages: UsageRecord[],
};

/**  Skill 元数据，对应 ~/.claude/skills/<id>/ 目录 */
export type Skill = {
	id: string,
	name: string,
	description: string,
	content: string,
	disableModelInvocation: boolean,
	userInvocable: boolean,
	isActive: boolean,
	createdAt: number,
	updatedAt: number,
	isSymlink: boolean,
	hasSymlinkContent: boolean,
	linkTarget: string | null,
};

/**  新增/更新 Skill 的数据传输对象 */
export type SkillData = {
	id: string,
	name: string,
	description: string,
	content: string,
	disableModelInvocation: boolean,
	userInvocable: boolean,
};

export type SkillDirectoryImportResult = {
	skills: Skill[],
	imported: string[],
	skipped: SkillDirectoryImportSkippedItem[],
};

export type SkillDirectoryImportSkipReason = "invalid-id" | "exists" | "missing-skill-md";

export type SkillDirectoryImportSkippedItem = {
	id: string,
	reason: SkillDirectoryImportSkipReason,
};

export type SkillFileTreeEntry = {
	path: string,
	kind: SkillFileTreeEntryKind,
	size: number,
	isBinary: boolean,
};

/**  支持文件树条目（SKILL.md 以外的文件和目录） */
export type SkillFileTreeEntryKind = "file" | "directory";

export type StatusLinePresetInstallResult = {
	presetId: string,
	targetPath: string,
	commandPath: string,
	installed: boolean,
	needsOverwrite: boolean,
};

/**  一个 subagent 侧链（按 agentId 聚合的子时间线） */
export type SubagentChain = {
	agent_id: string,
	slug: string | null,
	messages: SessionMessage[],
};

export type UnmanagedMemory = {
	id: string,
	name: string,
	content: string,
	targetType: MemoryTargetType,
	rulePath: string | null,
	pathPatterns: string[],
	sourcePath: string,
	size: number,
	modifiedAt: number,
	importStatus: string,
};

export type UnmanagedMemorySource = {
	targetType: MemoryTargetType,
	rulePath: string | null,
};

export type UnmanagedUserSettings = UnmanagedUserSettings_Serialize | UnmanagedUserSettings_Deserialize;

export type UnmanagedUserSettings_Deserialize = {
	sourcePath: string,
	settings: unknown,
	size: number,
	modifiedAt: number,
	importStatus: string,
	errorMessage: string | null,
	matchedProfileId: string | null,
};

export type UnmanagedUserSettings_Serialize = {
	sourcePath: string,
	settings: unknown,
	size: number,
	modifiedAt: number,
	importStatus: string,
	errorMessage?: string | null,
	matchedProfileId?: string | null,
};

/**  使用条目（工具和 Skill 通用） */
export type UsageEntry = {
	usageCount?: number,
	lastUsedAt?: number,
};

export type UsageFilter = {
	startDate?: string | null,
	endDate?: string | null,
	projectPath?: string | null,
	sessionId?: string | null,
	model?: string | null,
	includeUnknownModels?: boolean | null,
};

/**  单条 usage 原始记录 */
export type UsageRecord = {
	messageId: string,
	sessionId: string,
	projectPath: string,
	projectDir: string,
	timestampMs: number,
	model: string,
	inputTokens: number,
	outputTokens: number,
	cacheCreation5m: number,
	cacheCreation1h: number,
	cacheRead: number,
	costUsd: number | null,
	gitBranch: string | null,
	ccVersion: string | null,
};

/**
 *  用量页一次刷新的全量聚合视图：把 summary/daily/timeSeries/projects/sessions/models
 *  合并为单次 Tauri command 返回，避免前端 6 个 invoke 串行触发后端 7 次全表扫描。
 */
export type UsageSnapshot = {
	summary: UsageSummary,
	daily: DailyUsage[],
	timeSeries: UsageTimeSeriesPoint[],
	projects: ProjectUsage[],
	sessions: SessionUsage[],
	models: ModelUsageStat[],
};

export type UsageSummary = {
	totalMessages: number,
	totalSessions: number,
	totalProjects: number,
	totalInput: number,
	totalOutput: number,
	totalCacheCreation: number,
	totalCacheRead: number,
	totalCost: number | null,
	lastScanMs: number | null,
	pricing: PricingTable,
	thirdPartyProviderPricingEnabled: boolean,
	unknownModels: string[],
	allProjects: ProjectOption[],
	allModels: string[],
};

export type UsageTimeGranularity = "day" | "hour" | "fiveMinute";

export type UsageTimeSeriesPoint = {
	bucket: string,
	bucketStartMs: number,
	messages: number,
	sessions: number,
	inputTokens: number,
	outputTokens: number,
	cacheCreationTokens: number,
	cacheReadTokens: number,
	cost: number | null,
	inputCost: number | null,
	outputCost: number | null,
	cacheCreationCost: number | null,
	cacheReadCost: number | null,
	byModel: ModelUsageStat[],
};

export type UserSettingsImportInput = {
	name: string,
	description: string,
};

/**
 *  会话等待输入时播放的提示音效。
 *  变体映射到 macOS `/System/Library/Sounds/` 下的系统音效（映射见 `sound.rs`）。
 */
export type WaitingSound = "glass" | "submarine" | "hero" | "ping" | "sosumi" | "tink";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}
