import { readFileSync } from "node:fs";
import { relative } from "node:path";
import { describe, expect, it } from "vitest";

import { isTauri } from "./types";

const SOURCE_FILES = import.meta.glob("./**/*.{ts,tsx}", {
  eager: true,
  query: "?raw",
  import: "default",
}) as Record<string, string>;

const ALLOWED_DIRECT_INVOKE_FILES = new Set(["bindings.ts"]);
const TEST_FILE_PATTERN = /(^|\/)(?:__tests__\/.*|.*\.test\.[tj]sx?)$/;

describe("IPC usage contract", () => {
  it("keeps runtime environment detection outside generated bindings", () => {
    expect(typeof isTauri).toBe("function");
  });

  it("only lets generated bindings import Tauri invoke directly", () => {
    const offenders = Object.entries(SOURCE_FILES)
      .map(([path, content]) => ({
        path: relative(process.cwd(), path.replace(/^\.\//, "src/")),
        content,
      }))
      .filter(({ path }) => !TEST_FILE_PATTERN.test(path))
      .filter(({ path }) => !ALLOWED_DIRECT_INVOKE_FILES.has(path.replace(/^src\//, "")))
      .filter(({ content }) => content.includes("@tauri-apps/api/core"));

    expect(offenders.map(({ path }) => path)).toEqual([]);
  });

  it("keeps the submitted bindings artifact present for frontend builds", () => {
    const bindings = readFileSync("src/bindings.ts", "utf8");

    expect(bindings).toContain("This file has been generated by Tauri Specta");
    expect(bindings).toMatch(/\n$/);
    expect(bindings).not.toMatch(/\n\n$/);
  });

  it("keeps make bindings delegated to the Rust generator", () => {
    const makefile = readFileSync("Makefile", "utf8");

    expect(makefile).toContain("cd src-tauri && cargo run --bin generate_bindings");
    expect(makefile).not.toContain("perl -pi");
  });
});
